import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { AppHeader } from "../components";
import styles from "../styles/pages/product.module.scss";
import Product1 from "../assets/images/products/product1.png";
import Product3 from "../assets/images/products/product3.png";
import Product4 from "../assets/images/products/product4.png";
import Product5 from "../assets/images/products/product5.png";
import Product6 from "../assets/images/products/product6.png";
import Product7 from "../assets/images/products/product7.png";
import Product10 from "../assets/images/products/product10.png";
import Product11 from "../assets/images/products/product11.png";

const Products: NextPage = () => {
  return (
    <>
      <Head>
        <title>Our Product | Omegacoat LTD - Quality paint closer to you</title>
      </Head>
      <AppHeader />
      <section className={styles.ProductPage}>
        <h2 className={styles.title}>Product from us</h2>
        <p className={styles.txt}>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa quos,
          minima fugiat itaque dicta tenetur!
        </p>
        <div className={styles.thumb_content}>
          <div className="li1">
            <h3 className={styles.content}>Terms and Conditions</h3>
            <p className="detail">
              omega coat site is an easy to use platform, which helps you with
              our quabntity products, omegacoats has registered on hand painters
              which can be requested for via phone call to the company .
            </p>
            <h4>Terms</h4>
            <p className="detail" />
            Product – This refers to products owned by omega coat and allied
            products with proper license for sells and production.
            <br />
            <p>
              Illustrator – This is the term given to an application page on
              omega coat site which help with to select your color and preview
              on a vector graphic image for better user experience.
            </p>
            <h4>Conditions</h4>
            <p className="detail">
              No payment should or will be carried out on the on the site. This
              will be temporary as work to implement online payment are put in
              place. All content found on our site are generated by omegacoats
              and can be subject to copy right policy
            </p>
          </div>
          <div className="li2">
            <h3 className={styles.content}>How to use omega illustrator</h3>
            <p className="detail">
              omega illustrator is a color filled applicaton that allows you to
              preview desired colors on a vcetor image. This gives you a feel of
              how your home(any desire work flow) would look like when it is
              done with your the color you have in mind.
              <br /> This can be accessable for screen sizes higher than
              600px(pexels) by 500px(pexels), meaning havinrg higher screen
              dimensions such as tablets,ipads, mini screen laptops, desktops,
              laptops(15 inches and 17 inches) or high pexelated displays of
              some oled screens <br />
              <br /> warning: due to difference in screeen color resolution and
              picture quality if need be and you need an extact shade it is
              advice to further confirm the shade of the color(our address can
              be found on the site)
            </p>
            <h5>getting started using the omega illustrator</h5>
            <li>paint board</li>
            <p>
              This is used to pick out an illustrations to work on and edit the
              view color to give you that vector image imagination
            </p>
            <li>Color fill</li>
            <p>
              This is a tool used to apply your seleated color to fill out a
              section either first or second
            </p>
            <li>order button</li>
            <p>This is a button that gives you access to the order page </p>
            <li>using square meter quantity prediction</li>
            <p>
              This is a tool set in place to add better customer experience
              giving you the ability to input quantity needed through provided
              square meter of the area the paint would be used to cover. This
              works of a proven cover range of each paint product per liter but
              subject to variation of 0.9%
            </p>
          </div>
          <div className="li3">
            <h3 className={styles.content}>Paint types &amp; catergories</h3>
            <br />
            <br />
            <br />
            <br />
            <span className={styles.topic}>OMEGA TRADE (SATIN):</span> <br />
            <br />
            <div className="productBox">
              <Image
                width={300}
                height={500}
                layout="responsive"
                className={styles.image}
                src={Product1}
                alt="OMEGA TRADE (SATIN) sample"
              />
              <h3>OMEGA TRADE (SATIN)</h3>
            </div>
            <p>System: Based on water dilutable Vinyl dispersion</p>
            <ul>
              <ol>Properties</ol>
              <li>
                The film is tough/durable and exhibit excellent scrub and
                abrasion resistance.
              </li>
              <li> Low water absorption and dirt pick-up</li>
              <li>
                The film is adequately protected against Microbial attack in the
                service environment.
              </li>
              <li>
                Excellent adhesion to substances/ high resistance to alkali/ no
                blister and chalking.
              </li>
              <li> Film is washable</li>
            </ul>
            <span className="sub_topic">Application:</span>
            <ul className="sub_object">
              <span className="list_heading">(a) Brush/roller or spray</span>
              <p>
                Coverage: - This depends on surface porosity. However/ the
                coverage is up to 4.2sq meter per 1 litre of satin paint.
              </p>
              <p>
                Uses - Highly protective and decorative. Architectural finish
                for exterior and interior surfaces.
              </p>
              <p>
                Availability:- Stocks are available several beautiful colour.
                However, colours outside the range of our colour chart are
                acceptable and produced at economic quantities.
              </p>
              <p>
                Safety Precaution: - Avoid contact with eyes and skin. In case
                of contact, wash affected part thoroughly with clean water.
                Obtain medical attention immediately if irritation occurs.
              </p>
              <p>Pack Size: - 4 litres and 20 litres</p>
              <span className={styles.topic}>Unique Emulsion paint:</span>{" "}
              <br />
              <br />
              <div className="productBox">
                <Image
                  width={300}
                  height={500}
                  layout="responsive"
                  className={styles.image}
                  src={Product6}
                  alt="Unique Emulsion sample"
                />
                <h3>Unique Emulsion paint</h3>
              </div>
              <p>
                System: - Based on water dilutable pure acrylic polymer
                dispersion
              </p>
              <ul className="sub_object">
                <ol>Properties:</ol>
                <li>
                  The film exhibits high durability and good scrub resistance
                </li>
                <li>
                  Very good adhesion to substrate, high resistance to blisters
                  and chalking
                </li>
                <li>Low water absorption and low dirt pick-up</li>
                <li>
                  The film is adequately protected against microbial attack in
                  the service environment.
                </li>
              </ul>
              <ul className="sub_object">
                <ol>Application: </ol>
                <p>The following procedure is advisedly allowed</p>
                <li>Newly plastered surfaces</li>
                <li>
                  Allow plastered surface 4-6 weeks drying period. Sand surface
                  with coarse paper to remove sharp nibs
                </li>
                <li>
                  Thin 4 litres unique emulsion slightly 0.5 litre of clean
                  water and stir very well. Then apply with clean brush or
                  roller and allow 30 minutes for painted surface before
                  applying the second coat.
                </li>
                <li>
                  Second coat- Thin as above, stir thoroughly and apply with
                  clean brush or roller. Allow surface to dry for 40-60 minutes
                  before applying third coat.
                </li>
              </ul>
              <ul className="sub_object">
                <ol>Previously pained surface.</ol>
                <li>
                  Scrape off surface to remove loosely bound paint films and
                  sand thoroughly to remove sharp nibs.
                </li>
              </ul>
              <ul className="sub_object">
                <ol>Coverage: </ol>
                <li>
                  When applied as directed, 1 litre of UniqueEmulsion paints
                  should cover 2-2.5 sq metre of a new surface depending on
                  porosity and surface roughness.
                </li>
              </ul>
              <ul className="sub_object">
                <ol>Availability:</ol>
                <p>
                  Stocks are available in several beautiful colours. However,
                  colours outside this range are acceptable and produced at
                  economic quantities.
                </p>
              </ul>
              <p>Pack Size: - 4 litres and 2o litres</p>
              <p>Storage Precaution: - Store in cool, dry condition</p>
              <ul className="sub_object">
                <ol>Safety Precaution: </ol>
                <li>Avoid skin and eye contact</li>
                <li>Adequate ventilation is required</li>
                <li>
                  In case of contact wash affected part thoroughly with
                  appropriate Thinner and clean water. obtained medical
                  attention if irritation occurs
                </li>
              </ul>
              <p>
                Recommendation: For special and multicoat application involving
                thinner, primer and topcoat, it is advisable that the entire
                paint is sourced from the same producer for case of
                compatibility and enhanced product performance.
              </p>
              <p>
                The information provided on this sheet is for guidance only and
                subject to modification from time to time in the light of
                experience and advanced technology.
              </p>
              <br />
              <br />
              <br />
              <br />
              <span className={styles.topic}>Unique Textured Finish:</span>{" "}
              <br />
              <br />
              <div className="productBox">
                <Image
                  width={300}
                  height={500}
                  layout="responsive"
                  className={styles.image}
                  src={Product7}
                  alt="Unique Textured sample"
                />
                <h3>unique textured paint</h3>
              </div>
              <p>
                System: - based on water dilutable pure acrylic polyer
                dispersion
              </p>
              <ul>
                <ol>Properties: </ol>
                <li>
                  film is tough, durable and exhibit excellent scrub and
                  abrasion resistance.
                </li>
                <li>
                  Excellent adhesion to substrate, high resistance to Alkall, no
                  blisters and chalking
                </li>
                <li>
                  With high obliteration power at one coat, textured finish
                  hides all surface imperfections of previously painted surface
                </li>
                <li>
                  Exhibit very beautiful patterns (when rollers are sued) that
                  are permanently retained throughout the life of the paint film
                </li>
                <li>Lower water absorption and dirt pick up</li>
                <li>
                  The film is adequately protected against microbial attack in
                  the service environment .
                </li>
                <li />
              </ul>
              <p>
                Uses: - Highly protective and decorative architectural finish
                for exterior and interior surfaces.
              </p>
              <span className="sub_topic">Application:</span>
              <ul className="sub_object">
                <span className="listing_head">
                  Method:
                  <li>
                    Apply one coat of Omega textured finish directly on the
                    prepared surface with a roller which gives aregular and even
                    distribution of the texturing materials.
                  </li>
                </span>
              </ul>
              <ul>
                <ol>Covering Capacity: </ol>
                <li>
                  This depend on the type of applications and Surface porosity.
                  However, the coverage is 1.35sq meter per 1 litres
                </li>
              </ul>
              <p>
                Drying Time: - Touch in 1 ½ hours. Hard and touch dry overnight
              </p>
              <p>Packaging: - Unique textured is available in 30kg pail</p>
              <p>Storage: - Store in a cool and dry condition</p>
              <p>
                Safety: - Non toxic, environmentally friendly usage handing and
                disposal.
              </p>
              <p>
                Safety Precaution: - Avoid contact with eyes and skin. In case
                of contract, wash affected part thoroughly with clean water.
                Obtain medical attention immediately if irritation occurs.
              </p>
              <br />
              <br />
              <br />
              <br />
              <span className={styles.topic}>Exotic Emulsion paint:</span>{" "}
              <br />
              <br />
              <div className="productBox">
                <Image
                  width={300}
                  height={500}
                  layout="responsive"
                  className={styles.image}
                  src={Product1}
                  alt="Exotic Emulsion sample"
                />
                <h3>Exotic Emulsion paint</h3>
              </div>
              <p>
                This is a unique paint and one of the most popular paint product
                commonly used today, it can be used for both interior and
                exterior paint jobs because of its ability to hold on porous
                walls (surfaces) due to its watery make up and less smell. The
                paint has the ability to with stand the test of time giving you
                years of its shape or natural colors without fading.
              </p>
              <ol>face description</ol>
              <p>
                This paint product produces a smooth and fine finished paint job
                with no reflective effect (light bounce effect) to finally give
                a smart look which has high durable and covers a large surface
                area
              </p>
              <ul>
                <ol>Properties:</ol>
                <li>The film exhibits high durability and good </li>
                <li>Scrub resistance to blisters and chalking </li>
                <li>Low water absorption and low dirt pick-up</li>
                <li>The film is adequately protected against </li>
              </ul>
              <p>
                Microbial attack (i.e. brown and black fungi as well as green
                algae).
              </p>
              <span className="sub_topic">Application:</span>
              <ul className="sub_object">
                <span className="list_heading">
                  (a) Newly plastered surface
                  <span>Allow plastered surface 4-6 weeks drying</span>
                  <li> Sand surface with coarse paper to remove sharp nibs.</li>
                  <li>
                    Thin 4 liters Exotic emulsion slightly with 1 liters of
                    clean water and stir very well. Then apply with clean brush
                    or roller and allow 30 minutes for painted surface to dry
                    before applying the second coat.
                  </li>
                  <li>
                    Second coat- Thin as above, stir thoroughly and apply with
                    clean brush or roller. Allow surface to dry for 40-60
                    minutes before applying third coat.
                  </li>
                  <li>Third coat-as for second coat.</li>
                </span>
                <span className="list_heading">
                  Previously painted surface
                  <li>
                    Scrape off surface to remove loosely bound paint films and
                    sand thoroughly to remove sharp nibs.
                  </li>
                  <li>
                    - Then thin your 4 liters Exotic emulsion slightly with 1
                    liter of clean water stir very well before applying your
                    exotic emulsion pains with clean brush or roller. Allow 30
                    minutes drying time as first coat.
                  </li>
                  <li>
                    - Second coat-Repeat as for first coast and Allow overnight
                    drying before putting building into use
                  </li>
                  <li>
                    When applied as directed, 1 liter of exotic emulsion. Paint
                    should cover 4, 5-5 square meters of a new surface depending
                    on porosity and surface roughness.
                  </li>
                  <li>
                    Stocks are available several beautiful color. However,
                    colors outside the range of our color chart are acceptable
                    and produced at economic quantities.
                  </li>
                </span>
              </ul>
              <p>Pack Size: - 4 liters and 20 liters</p>
              <p>
                Safety Precaution: - Avoid contact with eyes and skin. In case
                of Contact, wash affected part thoroughly with clean water.
                Obtain medical attention immediately if irritation occurs.
              </p>
              <br />
              <br />
              <br />
              <br />
              <span className={styles.topic}>Exotic Textured Finish</span>
              <br />
              <div className="productBox">
                <Image
                  width={300}
                  height={500}
                  layout="responsive"
                  className={styles.image}
                  src={Product1}
                  alt="Exotic TEXTURED paint"
                />
                <h3>Exotic textured finish</h3>
              </div>
              <p>
                This product is a water based paint product which enhances the
                qualities of the surface its applied on. It is commonly used for
                exterior designs(building walls) for it ability to with stand
                harsh weather.
              </p>
              <ol>Properties:</ol>
              <li>
                Film is tough, durable and exhibit excellent scrub and abrasion
                resistance
              </li>
              <li>
                Excellent adhesion to substrate, high resistance to alkali, no
                blisters and chalking
              </li>
              <li>
                With high obliteration power at one coat, textured finish hides
                all surface imperfections of previously painted surface.
              </li>
              <li>
                Exhibit very beautiful patterns (when rollers are sued) that are
                permanently retained throughout the life of the paint film
              </li>
              <li>Lower water absorption and dirt pick up</li>
              <li>
                The film is adequately protected against microbial attack in the
                service environment.
              </li>
              <p>
                Uses: - Highly protective and decorative architectural finish
                for exterior and interior surface.
              </p>
              <span className="sub_topic">Application:</span>
              <ul className="sub_object">
                <span className="list_heading">
                  Method I
                  <li>
                    Surface must adequately be prepared by gentle sanding with
                    coarse sand paper to remove nibs.
                  </li>
                  <li>
                    - Apply one coat of Exotic Finish directly on the prepared
                    substrate with a foam roller which gives a regular and even
                    distribution of the texturing materials.
                  </li>
                </span>
                <span className="list_heading">
                  Method II
                  <li>
                    Apply Exotic Textured Finish directly on the prepared
                    surface with a special Texture brush.
                  </li>
                  <li>
                    Selected roller according to pattern you require and roll it
                    on the wet paint film from top to bottom slowly, keeping
                    your hand straight with some light pressure
                  </li>
                  <li>
                    - Second coat-Repeat as for first coast and Allow overnight
                    drying before putting building into use
                  </li>
                </span>
              </ul>
              <p>
                Recoat ability: - Not required, but re-decoration can be done
                either for a change of color to make surface new by brushing on
                it one or two coats of Exotic emulsion paint with your pattern
                still retained.
              </p>
              <p>
                Coverage: - This depend on methods of applications and Surface
                porosity however, for foam rollers Coverage is between 24-38
                square meters Per 20 liters while patterned methods is 5-7
                Square meter per 20 liters pail.
              </p>
              <p>Pack Size: - 20 liters</p>
              <p>
                Safety: - Nontoxic, environmentally friendly usage, Handling and
                disposal.
              </p>
              <p>
                Safety Precaution: - Avoid contact with eyes and skin. In case
                of contact, wash affected part thoroughly with clean water.
                Obtain medical attention immediately if irritation occurs.
              </p>
              <br />
              <br />
              <br />
              <br />
              <span className={styles.topic}> Unique Gloss Finish</span>
              <br />
              <br />
              <div className="productBox">
                <Image
                  width={300}
                  height={500}
                  layout="responsive"
                  className={styles.image}
                  src={Product11}
                  alt="Unique Gloss Finish sample"
                />
                <h3>Unique Gloss Finish</h3>
              </div>
              <p>
                This is an oil based product commonly known for it glossy look.
                The exotic gloss finish is mostly used for iron or wood works as
                it give a reflective effective (light bounce effect) and
                improves durability of the finished product.
              </p>
              <p>Type: - Single pack and air drying standard quality Enamel</p>
              <ol>Properties:</ol>
              <ul>
                <li>Exhibit good gloss and coverage</li>
                <li>Excellent fade resistance and light fastness</li>
                <li>Superb film adhesion that is hardwearing and durable.</li>
              </ul>
              <p>
                Use: - Protective and decorative enamel for exterior and
                interior surfaces with lasting and durable glossy finish.
              </p>
              <p>
                Application: - Stir well before use. Exotic Gloss can be applied
                on primed and unprimed concrete, metal and wood either by
                brushing or spraying methods.
              </p>
              <span className="list_heading">
                Unprimed Masonry
                <li>
                  Sand surface with coarse paper to remove sharp nibs. Tin 4
                  liters of gloss with approximately 1 liter of exotic thinner
                  turpentine or white spirit. Then apply with a clean brush and
                  allow 4-6 hours for painted surface to dry before re-coating.
                </li>
              </span>
              <span className="list_heading">
                Primed Masonry
                <li>
                  Substrate must be prepared adequately by sanding and cleaning
                  to remove sharp nibs.
                </li>
                <li>
                  Apply one coat of previously thinned exotic undercoat white
                  with a clean brush. Allow overnight drying. Sand gently and
                  apply two coats of exotic gloss as before for optimum results
                </li>
              </span>
              <span className="list_heading">
                Woodwork
                <li>
                  For best result, apply one coat of omega coat undercoat white.
                  Then allow overnight drying
                </li>
                <li>
                  Apply first coat of Exotic Gloss and allow 4-6 hours drying
                  time before re-coating.
                </li>
              </span>
              <span className="list_heading">
                Metals
                <li>
                  Metal surfaces must wiped with a clean rag previously soaked
                  in Exotic cleaning solvent to remove traces of grease or oils.
                </li>
              </span>
              <span className="list_heading">
                Previously Paint Surface
                <li>
                  With gloss or enamel paint scrape off loosely bound paints
                  with scrapper and apply two coats of Exotic paint.
                </li>
                <li>
                  With emulsion paint, scrape off as above and apply one coat of
                  Exotic undercoat before applying two coats of Exotic gloss.
                </li>
              </span>
              <p>
                Drying - Tack free dry 4-6 hours Hard dry over 12 hours Recoat
                ability after 6 hours
              </p>
              <p>
                Coverage - When applied as directed, 1 liter of Exotic gloss
                enamel should cover 4.5 square meters of a new concrete surface
                depending on porosity and surface roughness.
              </p>
              <p>
                Thinning - Exotic thinner turpentine is recommended for
                application purpose and cleaning up.
              </p>
              <p>
                Availability - Stocks are available several beautiful color.
                However, colors outside the range of our color chart are
                acceptable and produced at economic quantities.
              </p>
              <p>Pack Size - 4 liters or 20 liters</p>
              <p>Storage - Store in a cool dry condition</p>
              <p>
                Safety - Nontoxic, environmentally friendly in usage, handling
                and disposal.
              </p>
              <ol>Precaution</ol>
              <ul>
                Precaution
                <li>
                  Avoid contract with eyes skin. In case of contact wash
                  affected party thoroughly with white spirit and clean water
                  obtain medical attention immediately if irritation occurs.
                </li>
                <li>Keep away from sparks and open flames.</li>
              </ul>
              <br />
              <br />
              <br />
              <br />
              <span className={styles.topic}>SPLENDOUR EMULSION PAINT</span>
              <br />
              <br />
              <div className="productBox">
                <Image
                  width={300}
                  height={500}
                  layout="responsive"
                  className={styles.image}
                  src={Product10}
                  alt="SPLENDOUR EMULSION PAINT sample"
                />
                <h3>SPLENDOUR EMULSION PAINT</h3>
              </div>
              <p>
                System: - Based on water dilatable pure acrylic polymer
                dispersion
              </p>
              <ol>Properties:</ol>
              <ul>
                <li>
                  The film exhibits high durability and good scrub resistance
                </li>
                <li>
                  Very good adhesion to substrate, high resistance to blisters
                  and chalking
                </li>
                <li>Low water absorption and low dirt pick-up</li>
                <li>
                  The film is adequately protected against microbial attack in
                  the service environment.
                </li>
              </ul>
              <ol>Application:</ol>
              <ul>
                <span>The following procedure is advisedly allowed</span>
                <span className="list_heading">
                  Newly plastered surfaces
                  <li>
                    Allow plastered surface 4-6 weeks drying period. Sand
                    surface with coarse paper to remove sharp nibs.
                  </li>
                  <li>
                    Thin 4 liters splendor emulsion slightly 1 liter of clean
                    water and stir very well. Then apply with clean brush or
                    roller and allow 30 minutes for painted surface before
                    applying the second coat.
                  </li>
                  <li>
                    Second coat- Thin as above, stir thoroughly and apply with
                    clean brush or roller. Allow surface to dry for 40-60
                    minutes before applying third coat.
                  </li>
                  <li>Third coat- As for second coat.</li>
                </span>
                <span className="list_heading">
                  Previously pained surface.
                  <li>
                    Scrape off surface to remove loosely bound paint films and
                    sand thoroughly to remove sharp nibs.
                  </li>
                </span>
              </ul>
              <p>
                Coverage: - When applied as directed, 1 liter of Splendor
                Emulsion paints should cover 4-4.5 sq. meter of a new surface
                depending on porosity and surface roughness.
              </p>
              <p>
                Availability: - Stocks are available in forty two beautiful
                colors. However, colors outside this range are acceptable and
                produced at economic quantities.
              </p>
              <p>Pack Size: - 4 liters and 2o liters</p>
              <p>Storage Precaution - Store in cool, dry condition</p>
              <ul>
                <h4>Safety Precaution: -</h4>
                <li>Avoid skin and eye contact</li>
                <li>Adequate ventilation is required</li>
                <li>
                  In case of contact wash affected part thoroughly with
                  appropriate thinner and clean water. Obtained medical
                  attention if irritation occurs
                </li>
              </ul>
              <p>
                Recommendation: For special and multicoated application
                involving thinner, primer and topcoat, it is advisable that the
                entire paint is sourced from the same producer for case of
                compatibility and enhanced product performance. The information
                provided on this sheet is for guidance only and subject to
                modification from time to time in the light of experience and
                advanced technology.
              </p>
              <br />
              <br />
              <br />
              <br />
              <span className={styles.topic}>SPLENDOUR TEXTURED FINISH</span>
              <br />
              <br />
              <div className="productBox">
                <Image
                  width={300}
                  height={500}
                  layout="responsive"
                  className={styles.image}
                  src={Product10}
                  alt="SPLENDOUR TEXTURED FINISH sample"
                />
                <h3>SPLENDOUR TEXTURED FINISH</h3>
              </div>
              <p>
                System: - based on water dialutable pure acrylic polymer
                dispersion
              </p>
              <ol>Properties: </ol>
              <ul>
                <li>
                  film is tough, durable and exhibit excellent scrub and
                  abrasion resistance.
                </li>
                <li>
                  Excellent adhesion to substrate, high resistance to Alkali, no
                  blisters and chalking
                </li>
                <li>
                  With high obliteration power at one coat, textured finish
                  hides all surface imperfections of previously painted surface
                </li>
                <li>
                  Exhibit very beautiful patterns (when rollers are sued) that
                  are permanently retained throughout the life of the paint film
                </li>
                <li> Lower water absorption and dirt pick up</li>
                <li>
                  The film is adequately protected against microbial attack in
                  the service environment.
                </li>
              </ul>
              <p>
                Uses: - Highly protective and decorative architectural finish
                for exterior and interior surfaces.
              </p>
              <p>
                Application: Method: - Apply one coat of Omega textured finish
                directly on the prepared surface with a roller which gives a
                regular and even distribution of the texturing materials.
              </p>
              <p>
                Covering Capacity: - This depend on the type of applications and
                Surface porosity. However, the coverage is between 25-3 m2/20
                liters (20kg)
              </p>
              <p>
                Drying Time: - Touch in 1 ½ hours. Hard and touch dry overnight
              </p>
              <p>Packaging - Splendor textured is available in 30kg pail</p>
              <p>Storage - Store in a cool and dry condition</p>
              <p>
                Safety - Nontoxic, environmentally friendly usage, handling and
                disposal.
              </p>
              <p>
                Safety Precaution - Avoid contact with eyes and skin. In case of
                contract, wash affected part thoroughly with clean water. Obtain
                medical attention immediately if irritation occurs.
              </p>
              <br />
              <br />
              <br />
              <br />
              <span className={styles.topic}>SPLENDOUR GROSS FINISH</span>
              <br />
              <br />
              <div className="productBox">
                <Image
                  width={300}
                  height={500}
                  layout="responsive"
                  className={styles.image}
                  src={Product11}
                  alt="SPLENDOUR GROSS FINISH sample"
                />
                <h3>SPLENDOUR GROSS FINISH</h3>
              </div>
              <p>
                System: - Based on hardwearing long oil modified alkyd resin
              </p>
              <p>Types: - single pack and air drying standard quality enamel</p>
              <ol>Properties:</ol>
              <ul>
                <li> The film exhibits good gloss and coverage</li>
                <li>Excellent fade resistance and light fastness</li>
                <li>Superb film adhesion that is hard wearing And durable</li>
              </ul>
              Uses: - Protective and decorative enamel for exterior and interior
              <ol>Application:</ol>
              <ul>
                <p>
                  Stir well before use. Splendor Gloss can be applied on primed
                  and unprimed concrete, metal and wooden substrate either by
                  bushing or spraying methods.
                </p>
                <li>
                  Unprimed Masonry and surface with coarse paper to remove sharp
                  nibs
                </li>
                <li>
                  Thin 4 liters splendor gloss with approximately 0.5 liter of
                  thinner. Then apply with clean brush and allow 4-6 hours for
                  painted surface to dry before recoating
                </li>
                .
                <span className="list_heading">
                  Primed Masonry
                  <li>Substrate must be prepared to remove sharp nibs</li>
                  <li>
                    Apply first coat of splendor gloss and allow 4-6 hours
                  </li>
                  <li>drying time before recoating</li>
                </span>
                <li className="list_heading">Metals</li>
                <li>
                  Metal surface must be wiped with a clean rag previously soaked
                  in exotic cleaning solver it to remove traces of grease or
                  oils
                </li>
                <li>
                  Then sand surface gently to remove light rusts scales applying
                  a coat of splendor undercoat
                </li>
                <li>Lastly, apply two coats of splendor paint surface</li>
                <ol>Previously Painted surface</ol>
                <li>
                  With gloss or enamel paint, scrape off loosely bound paint
                  with scrapper and apply two coats of splendor paint.
                </li>
                <li>
                  With emulsion paint, scrape off as above and apply one coat of
                  splendor undercoat before applying two coats of splendor
                  gloss.
                </li>
              </ul>
              <ol>Drying:</ol>
              <ul>
                <li>Track free dry 4-6 hours</li>
                <li>Hard dry over 12 hours</li>
                <li>Re-conatability after 6 hours</li>
              </ul>
              <p>
                Coverage: - When applied as directed, 1 liter of splendor gloss
                enamel should cover 3.5 sq. meters of a new concrete surface
                depending on porosity and surface roughness.
              </p>
              <p>
                Thinning: - Exotic thinner turpentine is recommended for
                application purpose and cleaning up.
              </p>
              <p>
                Availability: - Stocks are available in forty two beautiful
                colors. However colors outside this range are acceptable
                produced at economic quantities.
              </p>
              <p>Pack Size: 4 liters 20 liters</p>
              <p>Storage Precaution - Store in cool, dry condition</p>
              <p>
                Recommendation: For special and multicoat application thinner,
                primer and topcoat, it is advisable that the entire paint
                systems is sourced from the same producer for case of
                compatibility and enhance product performance. The information
                provided on this sheet is for guidance only and subject to
                modification now time to time in the light of experience and
                advanced technology
              </p>
              <br />
              <br />
              <br />
              <br />
              <span className={styles.topic}>EXOTIC AUTO COLOUR RE-FINISH</span>
              <br />
              <br />
              <div className="productBox">
                <Image
                  width={300}
                  height={500}
                  layout="responsive"
                  className={styles.image}
                  src={Product11}
                  alt="EXOTIC AUTO COLOUR RE-FINISH"
                />
                <h3>EXOTIC AUTO COLOUR RE-FINISH</h3>
              </div>
              <p>System: - based on chain stopped fast drying alkyd resign</p>
              <p>
                Uses: - A highly durable all-purpose refinish for motor cars,
                commercial vehicles and metal furniture industrial and domestic.
              </p>
              <p>
                Properties: - Excellent opacity and nigh gloss. The paint has
                superb adhesion and good gloss Retention The film is
                non-yellowing with good color retention Good color retention
              </p>
              <p>
                Color: - We stock 25 beautiful solid colors drawn from
                international auto refinish codes. Others colors can produced on
                request at economic quantities
              </p>
              <p>Special Gravity: - 1.10+0.1</p>
              <p>Viscosity: - 120 seconds using BSB4 cup 25oc</p>
              <p>Solid Contents: - 55-60%</p>
              <p>
                Application: - For optimum result, spraying application is
                Recommended though brushing or dipping can be Where necessary.
              </p>
              <ol>Drying Time:</ol>
              <ul>
                <li>Touch Dry - 30 minutes</li>
                <li>Tack free dry - 2 ½ hours</li>
                <li>Hard dry - 5 hours</li>
              </ul>
              <p>Stoving schedule - 25oc for 1 hour</p>
              <p>Thinner: - Exotic auto thinner is usually recommended</p>
              <p>Packaging - 1 liter pack size of six liters per carton</p>
              <p>
                Storage - Paints are generally inflammable hence store in Cool,
                dry condition
              </p>
              <p>
                Safety - Nontoxic, environmentally friendly usage, handling and
                disposal.
              </p>
              <p>
                Recommendation: For multicoated applications, it is always
                advisable that the entire paint system including thinner are
                sourced from the same producer for case of compatibility and
                enhanced excellent mode performance.
              </p>
              <br />
              <br />
              <br />
              <br />
              <span className={styles.topic}>OMEGA RED OXIDE PRIMER</span>
              <br />
              <br />
              <div className="productBox">
                <Image
                  width={300}
                  height={500}
                  layout="responsive"
                  className={styles.image}
                  src={Product5}
                  alt="OMEGA RED OXIDE PRIMER"
                />
                <h3>OMEGA RED OXIDE PRIMER</h3>
              </div>
              <p>
                Description- This is a paint product severed as an
                undercoat/primer for iron, steel or materials prone to rust to
                prevent corrosion. They are red in color and product a fine oil
                finish with little or no glossy effect
              </p>
              <p>
                System: - Esterifies alkyd resign High build primer based on
                long oil
              </p>
              <p>
                Uses: - It is used mainly as a base coat for iron and steel To
                prevent rusting and corrosion of the metals
              </p>
              <p>
                Application: - Usually by brushing but can also be applied by
                spraying methods. Two coats of application is recommended for
                optimum performance on a clean, dry but degreased substrate.
              </p>
              <p>
                Drying Time: - Touch dry is between 3-4 hours depending on
                temperature and relative humidity. True drying is after 24
                hours.
              </p>
              <p>
                Coverage: - 8-10 square meter per liter depending on surface
                Preparations
              </p>
              <p>
                Thinning: - Exotic Thinner turpentine is recommended in a small
                quantity where slight thickening of primer is encountered for
                ease of application – brushing or spraying.
              </p>
              <p>
                Availability: - Stocks are available in forty two beautiful
                color however, colors outside this range are acceptable and
                produced at economic quantities.
              </p>
              <p>Pack Size: - 4 liters and 20 liters</p>
              <p>
                Storage : - Store in cool, dry condition They are inflammable
                hence keep away from Sparks and open flames. No smoking
              </p>
              <ol>Safety Precaution:</ol>
              <ul>
                <li> Avoid skin and eye contact</li>
                <li> Adequate ventilation is required</li>
                <li> Keep away from sparks and open flames</li>
                <li>
                  In case of contact wash affected part thoroughly with
                  appropriate thinner (turpentine) and clean water. Obtained
                  medical attention if irritation occurs.
                </li>
              </ul>
              <p>
                Recommendation: For special and multicoated application
                involving thinner, primer and topcoat, it is advisable that the
                entire paint system is spruced from the producer for case of
                medication from time to time in the light of experience and
                advanced technology.
              </p>
              <br />
              <br />
              <br />
              <br />
              <span className={styles.topic}>OMEGA UNDERCOAT</span>
              <br />
              <br />
              <div className="productBox">
                <Image
                  width={300}
                  height={500}
                  layout="responsive"
                  className={styles.image}
                  src={Product11}
                  alt="OMEGA UNDERCOAT"
                />
                <h3>OMEGA UNDERCOAT</h3>
              </div>
              <p>
                Property - High build primer based on long oil esterified alkyd
                resin
              </p>
              <p>
                Description - This is a pre-coating paint enhancement product
                used as a stain remover to give a clean finish when the main
                paint product is applied. It can’t be used to cover holes or
                dints but are good for stains on walls, ceiling materials and so
                on.
              </p>
              <p>
                Uses: - It is used mainly as a base coat for aluminum,
                Galvanized steel, block, and coat masonry It serves as a sealant
                for interior and exterior use.
              </p>
              <p>
                Application: - It can be applied by brush or spray. One coat of
                Application is recommended for optimum Performance on a clean
                surface
              </p>
              <p>Drying Time: - Humidity and temperature dependent. Tack</p>
              <p>
                Coverage: - 8-10 square meter per liter depending on surface
                Preparations
              </p>
              <p>
                Thinning: - Exotic Thinner turpentine is recommended in a small
                quantity where slight thickening of primer is encountered for
                ease of application – brushing or spraying.
              </p>
              <p>
                Availability: - Stocks are available in forty two beautiful
                color however, colors outside this range are acceptable and
                produced at economic quantities.
              </p>
              <p>Pack Size: - 4 liters and 20 liters</p>
              <p>
                Storage Precaution: - Store in cool, dry condition They are
                inflammable hence keep away from Sparks and open flames. No
                smoking
              </p>
              <ol>Safety Precaution:</ol>
              <ul>
                <li>Avoid skin and eye contact</li>
                <li>Adequate ventilation is required</li>
                <li> Keep away from sparks and open flames</li>
                <li>
                  In case of contact wash affected part thoroughly with
                  appropriate thinner (turpentine) and clean water. Obtained
                  medical attention if irritation occurs.
                </li>
              </ul>
              <p>
                Recommendation: For special and multicoated application
                involving thinner, primer and topcoat, it is advisable that the
                entire paint system is spruced from the producer for case of
                medication from time to time in the light of experience and
                advanced technology.
              </p>
              <br />
              <br />
              <br />
              <br />
              <span className={styles.topic}>OMEGA BRIGHT ALUMINIUM PAINT</span>
              <br />
              <br />
              <div className="productBox">
                <Image
                  width={300}
                  height={500}
                  layout="responsive"
                  className={styles.image}
                  src={Product5}
                  alt="OMEGA BRIGHT ALUMINIUM PAINT"
                />
                <h3>OMEGA BRIGHT ALUMINIUM PAINT</h3>
              </div>
              <p>
                System: - Based on high quality thermoplastic resin consisting
                mainly hydro carbon.
              </p>
              <p>Type: - Single pack and air drying</p>
              <p>
                Application: - Usually by brushing or spraying a maximum of two
                Coats application on a clean, dry and degraded Surface will give
                optimum performance of high luster finish.
              </p>
              <ol>Properties:</ol>
              <ul>
                <li>
                  it is used as a top coat against rust and corrosion on Iron,
                  steel and galvanized metal surface.
                </li>
                <li>
                  It also exhibits excellent metallic luster that is character
                  of best grade of aluminum pigment.
                </li>
                <li> Have superb film adhesion to substrates.</li>
              </ul>
              <p>
                Drying Time: - it dries fast by solvent evaporation Between 10 –
                15 Minutes.
              </p>
              <p>
                Coverage: - 8-10 square meter per liter depending on surface
                Preparations.
              </p>
              <p>
                Thinning: - This is not usually recommended but in exceptional
                Cases, it is advisable to use Exotic Thinner turpentine.
              </p>
              <p>Packaging: - 4 liters and 20 liters</p>
              <p>
                Storage: - For as long as containers are kept sealed and stored
                in good conditions the paint can be kept for over a year without
                deterioration. If there is slight settlement, reconstitute by
                gentle stirring.
              </p>
              <ol>Precaution:</ol>
              <ul>
                <li>
                  Avoid contact with the eyes and skin. In case of contact wash
                  affected part thoroughly with Exotic thinner and clean water.
                  Obtain medical attention if irritation occurs.
                </li>
                <li> Keep away from sparks and open flames</li>
              </ul>
              <br />
              <br />
              <br />
              <br />
              <span className={styles.topic}>
                OMEGA ROAD LINING PAINT – CHLORINATED RUBBER BASED
              </span>
              <br />
              <br />
              <div className="productBox">
                <Image
                  width={300}
                  height={500}
                  layout="responsive"
                  className={styles.image}
                  src={Product5}
                  alt="OMEGA ROAD LINING PAINT – CHLORINATED RUBBER BASED sample"
                />
                <h3>OMEGA ROAD LINING PAINT – CHLORINATED RUBBER BASED</h3>
              </div>
              <p>System: - Chlorinated Rubber</p>
              <p>Types: - Single pack and air drying</p>
              <p>
                Uses: - Hard, durable, weather resistant paints used in lining
                dual carriage ways, airport runways, pedestrian crossings,
                parking spaces etc.
              </p>
              <ol>Properties:</ol>
              <ul>
                <li>
                  The paint is hard wearing, quick drying and capable of
                  application to asphalt – surfaced roads.
                </li>
                <li>
                  The toughness of the films, their good adhesion coupled with
                  their outstanding resistance to weather condition particularly
                  in the tropic makes it ideal paint for roads
                </li>
              </ul>
              <p>
                Viscosity: - Supplied viscosity is normal 4 poises using the
                root Thinner
              </p>
              <p>
                Application: - By brush or road lining machine. For a good
                Performance of the paint film the substrate must be clean and
                dry.
              </p>
              <ol>Drying Time:</ol>
              <ul>
                <li>
                  Touch dry is between 5 to 8 minutes depending on temperature
                  and humidity.
                </li>
                <li>
                  The film will be impression free between 20 to 35 minutes to
                  be able to withstand vehicular pressure.
                </li>
              </ul>
              <p>
                Coverage: - 4-6 square meter per liter depending on surface
                Porosity and layer thickness of paint film.
              </p>
              <p>
                Thinner: - Exotic Nitrocellulose Thinner or thinner II is
                Recommended for viscosity adjustment, ease or Application plus
                general cleaning of materials and Equipment.
              </p>
              <p>Packaging: - 4 liters, 20 liters and 200 liters</p>
              <p>
                Storage: - If kept in cool, dry condition with container
                properly sealed, the product can be warehoused for over six
                months without deterioration. If slight setting is noticed
                thereafter, reconstitute by ordinary stirring.
              </p>
              <p>
                Availability: - Product is available in white color. However,
                other color can be produced to consumer’s specification at
                economic quantities.
              </p>
              <ol>Precaution:</ol>
              <ul>
                <li>
                  Avoid contract with the eyes and skin. In case of contact
                  thoroughly with thinner II and clean water.
                </li>
                <li> Keep away from sparks and open flames.</li>
              </ul>
              <br />
              <br />
              <br />
              <br />
              <span className={styles.topic}> OMEGA NITROCELLULOSE WOOD</span>
              <br />
              <br />
              <div className="productBox">
                <Image
                  width={300}
                  height={500}
                  layout="responsive"
                  className={styles.image}
                  src="/static/media/E (14)2.89109ca4.png"
                  alt="OMEGA NITROCELLULOSE WOOD"
                />
                <h3>OMEGA NITROCELLULOSE WOOD</h3>
              </div>
              FINISH GLOSSY
              <p>
                System: - Non pigmented high quality lacquer based on cellulose
                nitrate.
              </p>
              <ol>Properties: </ol>
              <ul>
                <li>
                  The film is hard and reasonably plasticized to prevent
                  cracking and other defects associated with various of weather
                  condition.
                </li>
                <li>
                  It dries fast within 5 minutes of application to a highly
                  durable film
                </li>
                <li>The film is high build with a superb finish gloss</li>
                <li>
                  It has an aromatic smell and exhibits good Flow on
                  application.
                </li>
                <li>
                  Good resistance to water, alcohols and household chemicals
                </li>
              </ul>
              <p>
                Users: - Protective and decorative lacquer finish for Wood work
                and furniture makers.
              </p>
              <ol> Application:</ol>
              <ul>
                <li>
                  For optimum results, spraying method of application is
                  advisable because of its fast drying nature.
                </li>
                <li>- Operational Procedure</li>
                <li>
                  - The wood surface must be seasoned, that is free from
                  excessive moisture.
                </li>
                <li>
                  - Surface should be sand papered smooth along the grain of the
                  wood to avoid leader Marks if sanded across.
                </li>
                <li>
                  - Apply wood filler after thinning to working consistency by
                  rubbing into wood grain and allow 5-30 minutes flash of time.
                </li>
              </ul>
              <br />
              <br />
              <br />
              <br />
              <span className={styles.topic}> P.O.P EMULSION</span>
              <br />
              <br />
              <div className="productBox">
                <Image
                  width={300}
                  height={500}
                  layout="responsive"
                  className={styles.image}
                  src={Product3}
                  alt="P.O.P EMULSION"
                />
                <h3>P.O.P EMULSION</h3>
              </div>
              <p>DESCRIPTION: - A premium quality emulsion wall screed</p>
              <h4>COMPOSITION:</h4>
              <p>
                PIGMENT: - Light fast prime pigments and selected Premium
                quality extenders
              </p>
              <p>
                BINDER: - Combination of acetate and acrylic co-polymer Emulsion
              </p>
              <p>
                USE: - A premium quality interior screed Formulated on high
                Quality emulsion binder to give an even Leaving on concrete
                block, cement. Render fibrous cement board, soft board, Asbestos
                rendering surface and brick Work.
              </p>
              <p>COLOUR RANGE: - BRILIANT WHITE</p>
              <p>PACK SIZE: - 20 LITTERS</p>
              <ol>PROPERTIES: </ol>
              <ul>
                <li>GLOSS LEVEL: - MATT</li>
                <li>CHEMICAL RESISTANCE: - Moderate alkali resistance</li>
                <li>SOLVENT RESISTANCE: - Poor</li>
                <li>SCRUB RESISTANCE: - Excellent wash ability</li>
                <li>HEAT RESISTANCE: - Not suitable for use on hot surface</li>
                <li>
                  WATER RESISTANCE: - Withstands humidity and rain, fully cured
                </li>
                <li>DURABILITY: - Excellent, provides superior durability</li>
                <li>OPACITY: - 1-COAT</li>
                <li>MOULD RESISTANCE: - Very good</li>
              </ul>
              <p>
                SPREADING RATE: - 8M2 / LITRE Depending on Application Methods,
                Condition, roughness and porosity
              </p>
              <ol>DRYING TIME: </ol>
              <ul>
                <li> TOUGH DRY: 20 minutes </li>
                <li> HARD DRY: OVER NIGHT</li>
              </ul>
              <p>
                SURFACES PREPARATION: - Remove all dirt’s, greases and flaking
                Paint, loose surface, powder and dead Algae. Repair cracks,
                holes and so on with Appropriate P.O.P wall screed materials.
              </p>
              <p>
                APPLICATION: <br /> - TROWEL: - Stir well and apply liberally
                straight from The container
              </p>
              <p>CLEANING / THINNER: - WATER</p>
              <br />
              <br />
              <br />
              <br />
              <span className={styles.topic}>
                {" "}
                OMEGA 50 FLOATING/SCREEING PAINT
              </span>
              <br />
              <br />
              <div className="productBox">
                <Image
                  width={300}
                  height={500}
                  layout="responsive"
                  className={styles.image}
                  src={Product4}
                  alt="OMEGA 50 FLOATING/SCREEING PAINT"
                />
                <h3>OMEGA 50 FLOATING/SCREEING PAINT</h3>
              </div>
              <p>DESCRIPTION: - A premium quality emulsion wall screed</p>
              <p>
                PIGMENT: - Light fast prime pigments and selected Premium
                quality extenders
              </p>
              <p>BINDER: - Combination of acetate and acrylic co-polymer</p>
              <p>
                USE: - A premium quality interior screed formulated on high
                quality emulsion binder to give an even leveling on concrete
                block, soft brick works.
              </p>
              <ol>COLOUR RANGE:</ol>
              <ul>
                <li>Selected range of OMEGA PAINTS and british standard</li>
                <li> A premium quality interior screed formulated on high</li>
              </ul>
              <p>PACK SIZE: - 20 LITTERS</p>
              <ol>PROPERTIES: </ol>
              <ul>
                <li>GLOSS LEVEL: - MATT</li>
                <li>CHEMICAL RESISTANCE: - Moderate alkali resistance</li>
                <li>SOLVENT RESISTANCE: - Poor</li>
                <li>SCRUB RESISTANCE: - Excellent wash ability</li>
                <li>HEAT RESISTANCE: - Not suitable for use on hot surfaces</li>
                <li>
                  WATER RESISTANCE: - Withstands humidity and rain, fully cured
                </li>
                <li>DURABILITY: - Excellent, provides superior durability</li>
                <li>OPACITY: - 1-COAT</li>
                <li>MOULD RESISTANCE: - Very good</li>
                <li>
                  SPREADING RATE: - 8M2 / liter depending on application
                  methods, condition, roughness and porosity
                </li>
                <li>DRYING TIME: - TOUGH DRY: 20 minutes,</li>
                <li>Hard Dry: Over Night HARD DRY: OVER NIGHT</li>
              </ul>
              <p>
                SURFACES PREPARATION: - Remove all dirt’s, greases and flaking
                Paint, loose surface, powder and dead Algae. Repair cracks,
                holes and so on with Appropriate P.O.P wall screed materials.
              </p>
              <p>
                APPLICATION: - Stir well and apply liberally straight from The
                container
              </p>
              <p>CLEANING / THINNER: - WATER</p>
              <br />
              <br />
              <br />
              <br />
              <br />
              <br />
            </ul>
          </div>
        </div>
      </section>
    </>
  );
};

export default Products;
